### ISSUE TITLE
Printing the source of a function from a module 

### ISSUE THREAD

**Issue by piccolbo** [mpastell/Pweave#106]
Hi, 
I would like to print a function from a module so that it's formatted like any code chunk, syntax highlighting and all. A use case could be I am writing an article about some standard library.
I know how to get the source with getsource and how to insert the output of getsource into the output file with the verbatim chunk option, but is there a way to process it through the same steps as code chunks? Thanks

**Comment by mpastell** [comment]
You can use the `source` chunk option http://mpastell.com/pweave/chunks.html#envvar-source

**Comment by piccolbo** [comment]
But that would read a whole file, correct?

**Comment by mpastell** [comment]
You can also use the name of the function as an argument and it will be added to the chunk using getsource: https://github.com/mpastell/Pweave/blob/eddee3b6f9024432dff85fc22e834c926a5adab1/pweave/processors/base.py#L117

**Comment by piccolbo** [comment]
I see. The error of my ways here is that I wanted a chunk with just that function, and so it just had
```
#+ source="mymodule.myfunction"
```

But then it gets skipped. If I add anything to the chunk, like `True`, then it works. May want to consider allowing empty chunk content for source chunk option. Thanks!
