### ISSUE TITLE
pygments.sty

### ISSUE THREAD

**Issue by AcidLeroy** [mpastell/Pweave#20]
Not sure if this is an issue, but when I install Pweave using pip there is no "pygments.sty" file. So when I attempt to run pdflatex after generating the .tex file I get the following error: 

! LaTeX Error: File `pygments.sty' not found.

I solved this by cloning the repo from github and pointing it to the "pygments.sty" file in the examples directory. I am running RHEL6 x86 and I have texlive installed. Do other distributions come with the "pygements.sty" file?

**Comment by mpastell** [comment]
pygments.sty is not part of any distribution, but you can create it for different styles using pygments:

```
pygmentize -S default -f tex > pygments.sty
```
See: http://pygments.org/docs/cmdline/#generating-styles

**Comment by AcidLeroy** [comment]
Just saw this! Thanks!

**Comment by abukaj** [comment]
Had exactly the same problem. I think you should mention it in the examples section of Pweave website.

**Comment by mpastell** [comment]
This is now added to the docs: http://mpastell.com/pweave/examples/index.html#latex-with-pygments-syntax-highlighting
