### ISSUE TITLE
using multiple input files

### ISSUE THREAD

**Issue by lbraglia** [mpastell/Pweave#22]
Hi Matti

thanks for Pweave.

Is there an equivalent of `\SweaveInput{}` for LaTeX input (eg `\PweaveInput{}`), in order to manage multiple input file?

thanks, 
  Luca

**Comment by mpastell** [comment]
Hi Luca,
There is no equivalent. What I usually do is to run Pweave separately on different documents and use `\include` in the main document to include the resulting files.

**Comment by lbraglia** [comment]
ok thanks for the hint
