### ISSUE TITLE
FIR_design.py example bug: undefined control sequence \textquotesingle

### ISSUE THREAD

**Issue by poleguy** [mpastell/Pweave#23]
This was sent as an email but no response. Maybe this is a better place to put this.

I just did a fresh install of pweave on a new win 7 machine. I'm getting an error in handling single quotes using your example. If I remove line 10 and 21 from the FIR_design.py file the error does not occur. It seems you may not be including the textcomp package. Can you confirm this bug and fix it?

Details below.

Possible fix?:
http://tex.stackexchange.com/questions/202166/undefined-control-sequence-textquotesingle

I'm running your example file with "pypublish -f pdf FIR_design.py"

I get the following error in the log file:

! Undefined control sequence.
<argument> \#\textquotesingle 
                              {}
l.123 ...ting with ``\texttt{\#\textquotesingle{}}
                                                  '' and
? 
! Emergency stop.
<argument> \#\textquotesingle 
                              {}
l.123 ...ting with ``\texttt{\#\textquotesingle{}}
                                                  '' and
End of file on the terminal!

 
Here is how much of TeX's memory you used:
 6554 strings out of 493921
 95649 string characters out of 3144873
 183050 words of memory out of 3000000
 9798 multiletter control sequences out of 15000+200000
 9654 words of font info for 33 fonts, out of 3000000 for 9000
 841 hyphenation exceptions out of 8191
 29i,6n,31p,245b,281s stack positions out of 5000i,500n,10000p,200000b,50000s
!  ==> Fatal error occurred, no output PDF file produced!

Attached is a list of the versions of software I have installed.

TortoiseSVN
1.8.11 64bit
Chrome
Cygwin
Python
2.7.10 and add to path
pip install matplotlib 1.4.3
pip install pweave
Pip install scipy 0.15.1
From http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy
Scipy-0.15.1-cp27-none-win32.whl
pip install numpy 1.9.2 from:
numpy‑1.9.2+mkl‑cp27‑none‑win32.whl
Pip install pygments for pweave
Pip install markdown for pweave
Pysvn
Visual C for Python:
http://aka.ms/vcpython27
http://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

MiKTeX
2.9.5105 Win32 (for pweave) from miktex.org/download
Set to Letter size default
 
Pandoc
To support pweave
1.15.0.6
https://github.com/jgm/pandoc/releases/tag/1.15.0.6
Pandoc.org

**Comment by mpastell** [comment]
Thanks for the report and sorry for the slow fix.
