### ISSUE TITLE
Feature request: interpret ansi output correctly.

### ISSUE THREAD

**Issue by stefanv** [mpastell/Pweave#39]
At the moment, converting markdown -> markdown, tracebacks etc. cause many uninterpreted unicode characters to appear in the output.

**Comment by mpastell** [comment]
Can you provide an example that fails?

**Comment by mpastell** [comment]
This is implemented in nbconvert and can be reused:
https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/ansi.py

I will try to move to using nbconvert for formatting anyway, but this could be useful to add to existing formatters as well.

**Comment by mpastell** [comment]
Or maybe use https://pypi.python.org/pypi/ansi2html/1.0.7

**Comment by mpastell** [comment]
This is now merged to master
