### ISSUE TITLE
Bokeh, Altair plotting

### ISSUE THREAD

**Issue by swayson** [mpastell/Pweave#41]
Hi there,

Only discovered this project today. I was wondering, whether reports can be generated with Bokeh/altair doing the plotting as opposed to Matplotlib? 

Both Altair and Bokeh render web-based graphics.

**Comment by mpastell** [comment]
Currently bokeh and altair are not supported. I have experimented running code using jupyter_client, which should work with any library that produces output in Jupyter notebooks. 

I don't know when I will have time to make it work properly.

**Comment by mpastell** [comment]
Current master executes code using the IPython kernel so you can make bokeh and altair work, but it looks like you will need to patch their display methods when running code outside of the browser.

**Comment by pchokanson** [comment]
@mpastell - Could you elaborate on what you meant by "patch their display methods"?  I was looking at how to fix (or at least work around) this, but some hints on where to start would be appreciated, if you have them.

**Comment by mpastell** [comment]
This is how you can use Bokeh right now (with master, not 0.25): https://gist.github.com/mpastell/6743ac4456979498549c2a7736a95a52

```
pweave -f md2html pweave_bokeh.pmd
```

By patching I mean that you could override the methods that Bokeh uses to displays plots in Jupyter notebooks (see: e.g. http://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display)

**Comment by pchokanson** [comment]
Thanks for the feedback.  I'm using Markdown, so I was able to get around this by printing the contents of `bokeh.embed.components()` directly into the HTML, which pandoc happily passes through.  Not an ideal solution, but it fits my current needs.  I think I could export raw SVG for LaTeX output in the future.

**Comment by mpastell** [comment]
I have added a few functions to work with Bokeh. This now works for `md2html` and markdown output (outputs raw html). 

```python
from bokeh.plotting import figure
from pweave.bokeh import output_pweave, show

output_pweave()

x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')
p.line(x, y, legend="Temp.", line_width=2)

show(p)
```
