### ISSUE TITLE
Missing macro on LaTeX

### ISSUE THREAD

**Issue by lgallindo** [mpastell/Pweave#47]
Just installed it using ```pip3 install pweave```. I downloaded FIR_design_verb.texw and ran:
```{bash}
pweave FIR_design_verb.texw
ptangle FIR_design_verb.texw
```

No errors are output, but the result .tex file is missing a macro definition: ```\PY```. Actually, many macros starting with ```\PY```.

**Comment by mpastell** [comment]
You'll need to use:

```
pweave -f tex FIR_design_verb.texw
```

See the example gallery http://mpastell.com/pweave/examples/index.html  for correct templates for other formats.
