### ISSUE TITLE
Inline strings from python code

### ISSUE THREAD

**Issue by briancohn** [mpastell/Pweave#48]
Any way for me to create a code chunk that will evaluate into Tex/Md? I'd love to write some inline statistics and interpretations.

Thanks!

**Comment by mpastell** [comment]
Yes. You can use output = "tex" or output = "md" chunk option for raw output. See http://mpastell.com/pweave/chunks.html#envvar-results='verbatim' .

**Comment by piccolbo** [comment]
One comment about this. I would like to print the src of a function from a library. I can grab the source with getsource, but when I try to print it  surrounded with `<pre> </pre>` I get `&lt;pre&gt;` in output. The chunk in py file is marked with `#+ results ="html". I am no longer sure what verbatim means, if markup gets quoted.
