### ISSUE TITLE
Unable to hide the code

### ISSUE THREAD

**Issue by ncdingari** [mpastell/Pweave#52]
I am using `pypublish -f pdf FIR_design.py` to make PDF. I would like to hide the code and I need only Document.

I tried the following, neither did work

```
```{python, echo=False}
n = 1001
a = signal.firwin(n, cutoff = [0.2, 0.5], window = 'blackmanharris', pass_zero = False)
mfreqz(a)
show()
```
```

and

```
<<echo=False>>=
n = 1001
a = signal.firwin(n, cutoff = [0.2, 0.5], window = 'blackmanharris', pass_zero = False)
mfreqz(a)
show()
@
```

**Comment by mpastell** [comment]
`echo=False` does hide python source code as documented. You'll need to use script syntax for options with `pypublish` http://mpastell.com/pweave/pypublish.html . Use `results=hidden`  to hide output as well
