### ISSUE TITLE
Add source of documentation

### ISSUE THREAD

**Issue by ghisvail** [mpastell/Pweave#53]
Please consider adding the source of the documentation (generated with Sphinx + rtd-theme I suppose) to the project's tree and shipping them in future PyPI release tarballs. Linux distributions primarily source themselves from PyPI and it would be desirable to enable builds of binary packages for both the Python modules / scripts and corresponding documentation.

Thanks,
Ghis

**Comment by mpastell** [comment]
The docs are now included in the repo and will be included in the next release.
