### ISSUE TITLE
fignos compatibiliy

### ISSUE THREAD

**Issue by farmlab** [mpastell/Pweave#57]
I have started to work with pweave and found it great. I am know trying to use [fignos](https://github.com/tomduck/pandoc-fignos) within my mdw file. It works fine except one aspect.  [fignos](https://github.com/tomduck/pandoc-fignos) uses the following convention `fig:id` to reference a figure. When I use such reference as name/label in my chunk the figure file is not produced due to the colon in the file name, e.g.:

Exemple (simplified!): 
```
<< name="fig:id", echo=False, caption="caption" >>=
make_figure()
@
```
produce:

`![caption](C:\...\figures/rapport_fig:id_1.png){#fig:id}`

Could it possible to treat the file name and the reference differently/separatly. I see two options:

1.  Clean the string name from special character such as colon
2.  Make the reference customizable, by default it use the name/label attribute, or it can be user defined for such a special case (my favorite)

or maybe I've missed something!

Thanks.

**Comment by mpastell** [comment]
I have now added cleaning of filenames, sorry for taking so long.

**Comment by farmlab** [comment]
Do not be sorry, thank you very much. I Will make a try.
