### ISSUE TITLE
Pweave 0.3 works in Python 3.6.1!

### ISSUE THREAD

**Issue by chendaniely** [mpastell/Pweave#66]
Probably should be added to the release notes.  I just installed `pweave` from source in a new `conda` environment with `python 3.6.1` and can confirm it works.

The current version in `conda`, `v0.25` will raise `UnsatisfiableError` in python 3.6*

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pweave -> python 3.3* -> openssl 1.0.1*
  - pweave -> python 3.3* -> xz 5.0.5
  - python 3.6*
```

**Comment by mpastell** [comment]
Fixed with https://github.com/conda-forge/pweave-feedstock/pulls for 0.25 and #70 for 0.3
