### ISSUE TITLE
Release 0.30?

### ISSUE THREAD

**Issue by mpastell** [mpastell/Pweave#71]
@rlaverde @abukaj @ccordoba12 

I received a request to release for 0.3. As far as I know (with not very active use lately) there are no blocking bugs or incomplete features in the current master. 

The blocking issue right now is that the documentation is not up to date. Would you like to see a release anyway with partially outdated documentation? Or would anyone have time see whats is broken in the docs at the moment? 

The docs are in https://github.com/mpastell/pweave-docs, and should also be moved under this repo.

**Comment by rlaverde** [comment]
Thanks for reviewing the pulls requests, and planning the 0.3 release 😄 

>would anyone have time see whats is broken in the docs at the moment?

I'm somehow familiar with the some of the changes introduced in 0.3, I've read parts of the code for making `spyder-reports` compatible with the current master. Tomorrow I'll give a try to update the docs

**Comment by ccordoba12** [comment]
Thanks @mpastell for contacting us about this new release!

@rlaverde, I think you should first move PWeave docs here, then update them and finally make them part of the package (I think all can be part of the same PR)

That way we could add a link in the welcome page of `spyder-reports` to point to PWeave docs.

**Comment by mpastell** [comment]
Thanks! With a quick look there aren't actually that many things that don't work with 0.3 in the docs, but mainly new features of are missing.

I think the major difference comes from getting output in nicer format with the jupyter display system.

Anyway I would feel comfortable doing a release with docs that are up to date even if some things are initially missing.

**Comment by abukaj** [comment]
Hi, sorry for the delay answering.

I am for pre-release rather than declaring it a stable one, since there is issue #61. It is not happening frequently, but it is IMHO jeopardizing idea of reproducibility.

**Comment by mpastell** [comment]
I have tried to investigate #61 and it is annoying, but I'm not sure if people will hit it during normal use. It seems to be a bug in `jupyter_client`, but I need to investigate further before making a bug report there.

**Comment by mpastell** [comment]
I have done some work on the docs and pushed updates to that repo. You can see the current status also at http://mpastell.com/pweave/0.3/index.html . I think they are almost ready for a release

**Comment by mpastell** [comment]
I pushed a pre-release 0.30rc1 to pypi. I tried using it with few of my larger documents as well and didn't find any issues.

**Comment by rlaverde** [comment]
I just take a look to the  updated docs, thanks for updating them, I was struggling with some little errors (missing ipykernel, and the term mode missing output),and didn't have time to start updating the docs.

It's something missing that I could help to do? could the docs be copied into the package to be distributed with it?

**Comment by ccordoba12** [comment]
> could the docs be copied into the package to be distributed with it?

Yes, if they are moved here. Please take a look at how we do it in Spyder.

**Comment by mpastell** [comment]
Yes, I'll move them before release. It was just quicker to work on the old repo.

**Comment by mpastell** [comment]
The docs are now in this repo. I just pushed Pweave v0.30 to pypi and will update the conda recipe. Thanks to all for the fixes!

**Comment by ccordoba12** [comment]
Thanks a lot @mpastell!
