### ISSUE TITLE
Multiple outputs from single chunk

### ISSUE THREAD

**Issue by mpastell** [mpastell/Pweave#76]
Currently running code that does multiple writes with delay produces several outputs, these should be merged as one.

```python
import sys
import time
sys.stdout.write("Hello\n")
time.sleep(2)
sys.stdout.write("Hello\n")
time.sleep(2)
sys.stdout.write("Hello\n")
```

```
Hello
```

```
Hello
```

```
Hello
```

**Comment by abukaj** [comment]
Already fixed it in the nondeterministicTestFail branch.

**Comment by mpastell** [comment]
Can you merge the fix to master?

**Comment by mpastell** [comment]
Cancel that, I'll fix it in formatters to keep the output compatible with `nbconvert`
