### ISSUE TITLE
No output when printing string 1-character long.

### ISSUE THREAD

**Issue by chendaniely** [mpastell/Pweave#78]
It seems that when trying to slice the first letter in a string, the results are not being stored

The pweave file:

```latex
\documentclass{article}

\begin{document}

<<>>=
word = 'word'
print(word[0])
@

<<>>=
word = 'word'
print(word[0:1])
@

<<>>=
word = 'word'
print(word[0:2])
@

<<>>=
word = 'word'
f = word[0]
print(len(f))
@

\end{document}
```

commands to create and view the document

```shell
pweave -f tex pweave_print.texw
pdflatex pweave_print.tex
xdg-open pweave_print.pdf
```

Here is the PDF output I'm getting:

![image](https://user-images.githubusercontent.com/5782147/29741853-c3540276-8a42-11e7-94fb-7b36ae2c543e.png)

**Comment by mpastell** [comment]
Which version of Pweave? I don't have this error using master.

**Comment by chendaniely** [comment]
```
pweave --version
Pweave 0.25
```

**Comment by chendaniely** [comment]
I'm using anaconda under a conda environment and installed it via:

`conda install -c conda-forge pweave`

**Comment by chendaniely** [comment]
For the time being, I'm setting the chunks to `evaluate=False` and manually copy/pasting the results in the following block

```latex
\begin{minted}[fontsize=\small, xleftmargin=0.5em, mathescape, frame = leftline]{text}
# python code output

\end{minted}
```

**Comment by mpastell** [comment]
I don't have the time to fix it for 0.25 right now. I recommend you try using current master. Or wait for 0.30 release which is almost ready.

**Comment by chendaniely** [comment]
I'll tinker around with various build and installations methods and report back.

**Comment by abukaj** [comment]
It is not about the slicing. I found minimal failing example (pweave 0.24):
```
<<>>=
print('a')
@
```

```
\begin{verbatim}
print('a')
\end{verbatim}
```

**Comment by mpastell** [comment]
I added a reference to the fix if you want to backport it to 0.25. This is fixed in 0.30, which is now released so I'll close this issue.

**Comment by chendaniely** [comment]
Sorry, didn't realize 0.3.0 was realized on the channels.
Everything seems to be in working order. Thanks!

**Comment by mpastell** [comment]
It wasn't when you opened the issue, glad that it's working
