### ISSUE TITLE
Column names are not indented when printing pandas dataframes

### ISSUE THREAD

**Issue by chendaniely** [mpastell/Pweave#81]
This seems to be something relatively new bug from 0.25 to 0.30

When printing out a dataframe, the column names are not indenting properly.
The column names are being printed completely left-justified, meaning that the first column name is directly above the row index label.

```shell
$ pweave --version
Pweave 0.30
```

sample document:

```tex
\documentclass{article}
\begin{document}

<<>>=
import pandas as pd
print(pd.__version__)
@

<<>>=
df = pd.DataFrame({
    'column1': [1, 2, 3],
    'column2': [4, 5, 6]
})
print(df)
@
\end{document}
```

compiling the document

```shell
# saved the above document as pweave_print.texw
pweave -f tex pweave_print.texw
pdflatex pweave_print.tex

# open the document
xdg-open pweave_print.pdf
```

output:
![image](https://user-images.githubusercontent.com/5782147/29776051-659444cc-8bd5-11e7-8a21-09d1a1a10cfc.png)

additional examples from my previously compiled documents:

old:
![image](https://user-images.githubusercontent.com/5782147/29776020-4ee6c66e-8bd5-11e7-86ee-2e9707f7f87d.png)

new:
![image](https://user-images.githubusercontent.com/5782147/29776005-40accc38-8bd5-11e7-95d9-57ef0cf50615.png)

Sorry about being overly active on the issue tracker.
Have a book manuscript due this week.
I can personally go back to 0.25 and use my hacky fix in #78, so there isn't any rush to fix the issue.
I can also try to fix it myself if I'm directed to the place to look...

**Comment by mpastell** [comment]
Thanks for the report, I think I fixed it as your example works with the latest commit and no tests were broken.

Thanks for reporting the bugs you encounter! There have been major changes since 0.25 and clearly the tests don't catch everything.

**Comment by chendaniely** [comment]
thanks! installed from latest source `Pweave 0.30.2dev` and everything seems to be working as expected
