### ISSUE TITLE
Documentation and use of 'term' option

### ISSUE THREAD

**Issue by jkroes** [mpastell/Pweave#83]
The script linked to on http://mpastell.com/pweave/pypublish.html includes `term=True` options, but the output in the PDF and HTML files don't output doctest strings, the behavior mentioned by http://mpastell.com/pweave/chunks.html. I also tried invoking the option using a variety of input and output formats, but it doesn't appear to do anything.

**Comment by jkroes** [comment]
I also tried using the `Pweb` class' `updateformat()` method, with no luck as shown below.
Note that test.py converts test.pmd to test.rst.

test.pmd:

```python, term=True
print("This is a test as well.")
```

test.py:

```
from pweave import Pweb
from pprint import pprint

doc = Pweb('source/test.pmd',
           doctype='rst',
           output='build/test.rst')

# pprint(doc.getformat())
doc.updateformat({'termstart': '.. code:: %s\n>>>',
                  'termend': 'anythingAtAll???'})
doc.weave()
```

test.rst:

```
.. code:: python

    print("This is a test as well.")


.. code::

    This is a test as well.
```

**Comment by mpastell** [comment]
Thanks for the report. That is an error in the documentation and has been left behind from 0.25, sorry for the confusion. I'll fix it. 

The reason for removing python terminal like formatting is because code is now always run using IPython and behavior can be different from plain Python terminal.
